import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import { notFound } from "next/navigation";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
});
const locales = ["sv", "en"];

export const metadata: Metadata = {
  title: "A ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: any };
}) {
  if (!locales.includes(locale)) notFound();

  return (
    <html lang={locale}>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
